name: michellemoore
favicon: null
layout_spectrum: 0.648650843417272
typography_spectrum: 0.15653518005274236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#c1c7c5'
    - '#000500'
    - '#304006'
    - '#7d9d21'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
