name: michellemoore
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6edfe'
    - '#d7545a'
    - '#c9c9c9'
    - '#e9a061'
    - '#d77179'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
